# Generated by Django 4.2.4 on 2023-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipeproduct',
            name='quatity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price'),
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Calculate name')),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('recipes', models.ManyToManyField(to='kvadro.recipe')),
            ],
        ),
    ]
