# Generated by Django 4.2.4 on 2023-09-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0002_remove_recipeproduct_quantity_recipeproduct_quatity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeproduct',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
