# Generated by Django 4.2.4 on 2023-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0003_rename_quatity_recipeproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
