# Generated by Django 4.2.4 on 2023-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0004_calculate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='count_man',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='calculate',
            name='count_people',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='calculate',
            name='count_woman',
            field=models.IntegerField(default=1),
        ),
    ]
