# Generated by Django 4.2.4 on 2023-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0005_calculate_count_man_calculate_count_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date update'),
        ),
    ]
