# Generated by Django 4.2.4 on 2023-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0006_alter_calculate_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date update'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date create'),
        ),
    ]
