# Generated by Django 4.2.4 on 2023-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvadro', '0007_calculate_update_date_alter_calculate_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='calculate',
            name='visitor_id',
            field=models.CharField(default='', max_length=200, verbose_name='Visitor ID'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Calculate name'),
        ),
    ]
